import { Injectable } from '@angular/core';
import { TOKEN_LIST } from '../models/token.model';
import {
  HistoryStream,
  HistoryStreamState,
  TransactionRecord,
  TransactionStatus,
  TransactionType,
} from '../models/transaction.model';
import { ROLL_PRICE_MAS } from './massa-provider';
import { fromUnits } from '../utils/token-amount';

/** Mainnet only — there is no public explorer API for buildnet. */
const EXPLORER_API = 'https://explorer-api.massa.net';
const MAS_DECIMALS = 9;

interface ExplorerOperation {
  readonly hash: string;
  /** Unix time in ms, as a string. */
  readonly block_time: string;
  readonly status: string;
  readonly type: string;
  readonly from: string;
  readonly to: string;
  /** nanoMAS, as a string — occasionally with a fractional part. */
  readonly value: string;
  readonly transaction_fee: string;
  readonly op_exec_status: boolean;
}

interface ExplorerOperationsResponse {
  readonly operationsCreated?: readonly ExplorerOperation[] | null;
  readonly operationsReceived?: readonly ExplorerOperation[] | null;
  /** Present only while the stream has more pages. */
  readonly nextCursorCreated?: string | null;
  readonly nextCursorReceived?: string | null;
}

export interface HistoryPage {
  /** Newest first. */
  readonly records: TransactionRecord[];
  /** New paging state, only for the stream(s) this request read. */
  readonly streams: Partial<Record<HistoryStream, HistoryStreamState>>;
}

const TOKEN_BY_CONTRACT = new Map(
  TOKEN_LIST.filter((t) => t.contract).map((t) => [t.contract, t.symbol]),
);

function shortAddress(address: string): string {
  return address.length > 12 ? `${address.slice(0, 6)}…${address.slice(-4)}` : address;
}

/** nanoMAS string → MAS. Drops any sub-nanoMAS fraction the API sometimes returns. */
function masFromNano(value: string): number {
  const whole = value.split('.')[0];
  return /^\d+$/.test(whole) ? fromUnits(BigInt(whole), MAS_DECIMALS) : 0;
}

function statusOf(op: ExplorerOperation): TransactionStatus {
  if (!op.op_exec_status) return 'failed';
  return op.status === 'Final' ? 'final' : 'pending';
}

function createdType(op: ExplorerOperation): TransactionType {
  switch (op.type) {
    case 'Transaction':
      return 'send';
    case 'BuyRoll':
      return 'buy_rolls';
    case 'SellRoll':
      return 'sell_rolls';
    default:
      return 'contract_call';
  }
}

function streamState(
  records: readonly TransactionRecord[],
  cursor: string | null | undefined,
): HistoryStreamState {
  return {
    cursor: cursor || null,
    oldest: records.reduce((min, r) => Math.min(min, r.timestamp), Infinity),
  };
}

/**
 * Reads an address's on-chain history from the Massa explorer API and
 * maps it to TransactionRecord.
 *
 * The explorer pages the two streams — operations the address created
 * (`from=true`) and received (`to=true`) — independently, 20 at a time,
 * each with its own opaque cursor. Without cursors a request returns the
 * newest page of both; with cursors, only the streams given.
 *
 * Received operations generated by a smart contract carry the caller's
 * operation hash plus a `_N` suffix; `operationId` strips it, so a call
 * and its payouts share one id.
 */
@Injectable({ providedIn: 'root' })
export class ExplorerApi {
  async getHistory(
    address: string,
    cursors?: Partial<Record<HistoryStream, string>>,
  ): Promise<HistoryPage> {
    const readCreated = !cursors || !!cursors.created;
    const readReceived = !cursors || !!cursors.received;

    const params = new URLSearchParams();
    if (readCreated) params.set('from', 'true');
    if (readReceived) params.set('to', 'true');
    if (cursors?.created) params.set('cursorCreated', cursors.created);
    if (cursors?.received) params.set('cursorReceived', cursors.received);

    const url = `${EXPLORER_API}/address/${encodeURIComponent(address)}/operations?${params}`;
    const response = await fetch(url);
    if (!response.ok) throw new Error(`Explorer API responded ${response.status}`);
    const body = (await response.json()) as ExplorerOperationsResponse;

    const created = (body.operationsCreated ?? []).map((op) => this.fromCreated(op));
    const received = (body.operationsReceived ?? []).map((op) => this.fromReceived(op));
    const streams: HistoryPage['streams'] = {};
    if (readCreated) streams.created = streamState(created, body.nextCursorCreated);
    if (readReceived) streams.received = streamState(received, body.nextCursorReceived);

    return {
      records: [...created, ...received].sort((a, b) => b.timestamp - a.timestamp),
      streams,
    };
  }

  private fromCreated(op: ExplorerOperation): TransactionRecord {
    const type = createdType(op);
    const amount = masFromNano(op.value);
    const token = TOKEN_BY_CONTRACT.get(op.to);
    return {
      ...this.base(op),
      type,
      amount,
      fee: masFromNano(op.transaction_fee),
      // Roll operations have no recipient ("-").
      counterparty: token ? `${token} contract` : op.to === '-' ? undefined : shortAddress(op.to),
      // For BuyRoll/SellRoll the explorer reports the MAS value (e.g.
      // 1500 MAS for 15 rolls), so the count comes from the roll price.
      rollCount:
        type === 'buy_rolls' || type === 'sell_rolls'
          ? Math.round(amount / ROLL_PRICE_MAS)
          : undefined,
    };
  }

  private fromReceived(op: ExplorerOperation): TransactionRecord {
    return {
      ...this.base(op),
      type: 'receive',
      amount: masFromNano(op.value),
      counterparty: shortAddress(op.from),
    };
  }

  private base(op: ExplorerOperation) {
    return {
      id: op.hash,
      operationId: op.hash.split('_')[0],
      token: 'MAS' as const,
      timestamp: Number(op.block_time),
      status: statusOf(op),
    };
  }
}
